apiVersion: v1
kind: Service
metadata:
  name: orbitops-api
  namespace: orbitops
spec:
  selector:
    app: orbitops-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
